[package]
name = "fine_calc"
version = "0.1.0"
edition = "2024"

[dependencies]
ncurses = "5.101.0"
lalrpop-util = { version = "0.22", features = ["lexer"] }
regex = "1"

[build-dependencies]
lalrpop = "0.22"
